
package Proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ProductWS", targetNamespace = "http://Webervice.soapserverpart.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductWS {


    /**
     * 
     * @return
     *     returns java.util.List<Proxy.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.GetAllProductsResponse")
    @Action(input = "http://Webervice.soapserverpart.example.com/ProductWS/getAllProductsRequest", output = "http://Webervice.soapserverpart.example.com/ProductWS/getAllProductsResponse")
    public List<Product> getAllProducts();

    /**
     * 
     * @param id
     * @return
     *     returns Proxy.Optional
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductById", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.GetProductById")
    @ResponseWrapper(localName = "getProductByIdResponse", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.GetProductByIdResponse")
    @Action(input = "http://Webervice.soapserverpart.example.com/ProductWS/getProductByIdRequest", output = "http://Webervice.soapserverpart.example.com/ProductWS/getProductByIdResponse")
    public Optional getProductById(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param product
     */
    @WebMethod
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.CreateProductResponse")
    @Action(input = "http://Webervice.soapserverpart.example.com/ProductWS/createProductRequest", output = "http://Webervice.soapserverpart.example.com/ProductWS/createProductResponse")
    public void createProduct(
        @WebParam(name = "product", targetNamespace = "")
        Product product);

    /**
     * 
     * @param id
     * @param product
     */
    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.UpdateProductResponse")
    @Action(input = "http://Webervice.soapserverpart.example.com/ProductWS/updateProductRequest", output = "http://Webervice.soapserverpart.example.com/ProductWS/updateProductResponse")
    public void updateProduct(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "product", targetNamespace = "")
        Product product);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://Webervice.soapserverpart.example.com/", className = "Proxy.DeleteProductResponse")
    @Action(input = "http://Webervice.soapserverpart.example.com/ProductWS/deleteProductRequest", output = "http://Webervice.soapserverpart.example.com/ProductWS/deleteProductResponse")
    public void deleteProduct(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

}
