
package Proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ProductWebServiceService", targetNamespace = "http://Webervice.soapserverpart.example.com/", wsdlLocation = "http://localhost:8088/?wsdl")
public class ProductWebServiceService
    extends Service
{

    private static final URL PRODUCTWEBSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException PRODUCTWEBSERVICESERVICE_EXCEPTION;
    private static final QName PRODUCTWEBSERVICESERVICE_QNAME = new QName("http://Webervice.soapserverpart.example.com/", "ProductWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTWEBSERVICESERVICE_WSDL_LOCATION = url;
        PRODUCTWEBSERVICESERVICE_EXCEPTION = e;
    }

    public ProductWebServiceService() {
        super(__getWsdlLocation(), PRODUCTWEBSERVICESERVICE_QNAME);
    }

    public ProductWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTWEBSERVICESERVICE_QNAME, features);
    }

    public ProductWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTWEBSERVICESERVICE_QNAME);
    }

    public ProductWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTWEBSERVICESERVICE_QNAME, features);
    }

    public ProductWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductWS
     */
    @WebEndpoint(name = "ProductWSPort")
    public ProductWS getProductWSPort() {
        return super.getPort(new QName("http://Webervice.soapserverpart.example.com/", "ProductWSPort"), ProductWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductWS
     */
    @WebEndpoint(name = "ProductWSPort")
    public ProductWS getProductWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Webervice.soapserverpart.example.com/", "ProductWSPort"), ProductWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PRODUCTWEBSERVICESERVICE_EXCEPTION;
        }
        return PRODUCTWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
